# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_llikFullPool2D <- function(Y, X, DICT1, DICT2, THETA, LINK, NCAT = 2L) {
    .Call(`_SPL_cpp_llikFullPool2D`, Y, X, DICT1, DICT2, THETA, LINK, NCAT)
}

cpp_grllFullPool2D <- function(Y, X, DICT1, DICT2, THETA, LINK, NCAT = 2L) {
    .Call(`_SPL_cpp_grllFullPool2D`, Y, X, DICT1, DICT2, THETA, LINK, NCAT)
}

cpp_get_dict <- function(LIST, NPAIRS) {
    .Call(`_SPL_cpp_get_dict`, LIST, NPAIRS)
}

