# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_llikFullPool2D <- function(Y, X, DICT1, DICT2, THETA, LINK, NCAT = 2L) {
    .Call(`_SPL_cpp_llikFullPool2D`, Y, X, DICT1, DICT2, THETA, LINK, NCAT)
}

cpp_grllFullPool2D <- function(Y, X, DICT1, DICT2, THETA, LINK, NCAT = 2L) {
    .Call(`_SPL_cpp_grllFullPool2D`, Y, X, DICT1, DICT2, THETA, LINK, NCAT)
}

#' Stochastic approximator
cpp_SA2 <- function(Y, X, LINK, DICT1, DICT2, START, STEP0, REPLACEMENT, TOL, STEP1 = 1, STEP2 = 1e-20, STEP3 = .75, SCHEDULE = 2L, UPDATE = 0L, SWITCH = 0L, AD1 = .9, AD2 = .999, PAIRS_PER_ITERATION = 8L, BURNE = 2L, MAXE = 3L, UPE = 1e4L, SEED = 123L, VERBOSE = 1L, NCAT = 2L, CHECK = TRUE) {
    .Call(`_SPL_cpp_SA2`, Y, X, LINK, DICT1, DICT2, START, STEP0, REPLACEMENT, TOL, STEP1, STEP2, STEP3, SCHEDULE, UPDATE, SWITCH, AD1, AD2, PAIRS_PER_ITERATION, BURNE, MAXE, UPE, SEED, VERBOSE, NCAT, CHECK)
}

#' Get indices contained in the pair, by pair idx
#' @export
cpp_shuffle <- function(VEC, K, SEED) {
    .Call(`_SPL_cpp_shuffle`, VEC, K, SEED)
}

#' @export
cpp_sample <- function(VEC, K, SEED) {
    .Call(`_SPL_cpp_sample`, VEC, K, SEED)
}

#' @export
cpp_sample2 <- function(VEC, K, SEED) {
    .Call(`_SPL_cpp_sample2`, VEC, K, SEED)
}

#' @export
cpp_sample3 <- function(VEC, K, SEED) {
    .Call(`_SPL_cpp_sample3`, VEC, K, SEED)
}

cpp_get_dict <- function(LIST, NPAIRS) {
    .Call(`_SPL_cpp_get_dict`, LIST, NPAIRS)
}

